### ISSUE TITLE
A paper on this work

### ISSUE THREAD

**Issue by good-demo** [Infinitywxh/Neural_Koopman_pooling#2]
Thanks for you sharing your work, I want to know where can I read your paper such as (arXiv).

**Comment by Infinitywxh** [comment]
Our paper is now available at CVF open access:
https://openaccess.thecvf.com/content/CVPR2023/papers/Wang_Neural_Koopman_Pooling_Control-Inspired_Temporal_Dynamics_Encoding_for_Skeleton-Based_Action_CVPR_2023_paper.pdf
