### ISSUE TITLE
您好，想咨询下E-Koopman的模型文件是koopman_pooling_emb.py嘛？

### ISSUE THREAD

**Issue by ikbears** [Infinitywxh/Neural_Koopman_pooling#3]

**Comment by Infinitywxh** [comment]
Eigenvalue normalization的代码实现在``eigen_normalization.py``中，具体训练方法请见``https://github.com/Infinitywxh/Neural_Koopman_pooling#training``。

**Comment by ikbears** [comment]
> Eigenvalue normalization的代码实现在`eigen_normalization.py`中，具体训练方法请见`https://github.com/Infinitywxh/Neural_Koopman_pooling#training`。

谢谢您
